yaml
name: Validate CloudFormation Templates

on:
  workflow_dispatch:

jobs:
  validate:
    name: Validate Templates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Test Step
      run: echo "Workflow structural configuration is successful!"
